version = 3.11.5
runner.dialect = scala3

maxColumn = 120
trailingCommas = always
align.preset = more
danglingParentheses.preset = true
indent.defnSite = 2
newlines.topLevelStatementBlankLines = [
  {
    blanks { after = 1 }
  }
]
